### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by dmudro** [GeekyAnts/NativeBase-KitchenSink#130]
I am trying to run your Kitchen Sink on iOS simulator locally but am seeing the same error as described in https://github.com/GeekyAnts/NativeBase-KitchenSink/issues/84.

Tried both options i. .e. `npm run ios` and build/run in Xcode - they both produce the same error:

![screen shot 2018-07-31 at 10 46 28](https://user-images.githubusercontent.com/1648143/43448773-0fce6d40-94af-11e8-9da2-279f059ac2ed.png)

On related note, previewing the app in Expo is also broken and third party projects would not show up as others described:
https://expo.io/@geekyants/nativebasekitchensink

As far as my experience is concerned, there no way to locally run the Kitchen Sink on iOS Simulator.

**Comment by SupriyaKalghatgi** [comment]
NativeBase KitchenSink on `master` is a pure react-native app, and i have confirmed that the app builds for both iOS and Android.

Regarding the demo at https://expo.io/@geekyants/nativebasekitchensink, this works for Android and not for iOS, due to expo not providing scan feature for iOS

To run NativeBase KitchenSink Expo app, you can run this locally `npm run ios` from branch `CRNA`
