### ISSUE TITLE
Can we get an update?

### ISSUE THREAD

**Issue by asharamseervi** [GeekyAnts/NativeBase-KitchenSink#138]
- NativeBase got update 2.8.0, but nothing new here.
- Hell, lots of updates from all over dependencies, but here, nothing to update and explore more possiblities.
- Expo, React, React-Native, Lodash, React Navigation and many more.

**In short, CRNA & RNRF is in deep fridge, winter is coming. Please, please update.**

**Comment by SupriyaKalghatgi** [comment]
@asharamseervi This is a free starter kit
Not difficult to update on your own

**Comment by asharamseervi** [comment]
Yes, I can with my fork. I tried and there are lots of ground breaking changes sine than. 

This is free does mean it will not be updated? Dependencies are core part of any project, please update this project soon. Or help me with this, I'll make an pull request.

**Comment by asharamseervi** [comment]
Hello @SupriyaKalghatgi, I had contributed to the project. Please check the pull request as referenced above. And merge it, so we can leverage of thousands of fixes at Expo, React & React-Native.

Thanks

**Comment by StevenBlack** [comment]
I'd like to respectfully say, yes, this is a "free" starter kit, but this is not a good starter kit anymore.

Comes a point when newcomers are led astray by aging repos, like this one.

In particular, if someone uses this repo to start an Expo project, using this as a skeleton (as it were),  looking for a Native Base-centric boost, then the user will discover, maybe considerable time later, that Expo categorically fails to build in production mode.

Speaking from experience, using this repo as a model may have been OK in the past, but it's not OK anymore.  

In my experience, you can get a nice app working from this repo, fantastic in fact, but come to Expo production mode, and you have to rip-out all the Native Base elements to get a production build.

I suggest that a written disclaimer may be in order here now.  It's the ethical thing to do.

**Comment by stevehorn** [comment]
@StevenBlack coming into React Native development fresh in the last week or so. Can you please help me understand what you mean by "Expo categorically fails to build in production mode"?  

Why do Native Base elements not work with Expo?

**Comment by StevenBlack** [comment]
@stevehorn I never found out.  I spent a few weeks developing a NativeBase sentric app, using this repo as a starter, and it was going great.  Until I tried to run in production mode.  

Error messages related to this just aren't helpful.  After quite awhile stripping components away, I isolated NativeBase as the culprit.  I did my best to dig deeper, to find the core issue, but I was unsuccessful.  I switched to [react-native-elements](https://github.com/react-native-training/react-native-elements) and no issues since.

Look, if you're going to use this repo as a starter, just know that you're hitching to an ancient version of Expo.  You're hitching to an ancient version of React Navigation.  This puts you in a tough place. 

On one hand, the Expo and React Native community are way ahead of your versions.  And on the other hand, the Native Base people are nice, but core developers just don't give a shit. They really don't; they have better things to do that worry about the Expo segment.  That's fair enough, I get it, and I understand.  But it would have been nice to know that, at the outset, this neat little starter kit is a dead-end trap.

In the end, I'm on Expo latest, React-Navigation latest, everything latest, and it's clear sailing.

**Comment by SupriyaKalghatgi** [comment]
We have been updating the `master` branch to React Native support.
Updating `master` with latest NativeBase and React Native(if stable) and `CRNA` in a day

**Comment by SupriyaKalghatgi** [comment]
@asharamseervi @StevenBlack @stevehorn `master` has latest of React Native and React Navigation

**Comment by SupriyaKalghatgi** [comment]
@asharamseervi @StevenBlack @stevehorn `CRNA` has latest of Expo, NativeBase and React Navigation

**Comment by StevenBlack** [comment]
Thank you Supriya @SupriyaKalghatgi!

**Comment by stevehorn** [comment]
Thanks for the update @SupriyaKalghatgi.  
When running the project now using `CRNA` branch (now using Expo), I get this stack trace in the iOS simulator: 
```
console.error: "The undocumented Modal API has been removed."

console.error
    YellowBox.js:69:10
Object.get
    Expo.js:123:12
_interopRequireWildcard
    <unknown file>:0
<unknown>
    <unknown file>:0
loadModuleImplementation
    require.js:214:4
guardedLoadModule
    require.js:148:11
_require
    require.js:132:2
<unknown>
    App.js:2
loadModuleImplementation
    require.js:214:4
```

The error seems to stem from `setup.js` on line 7 `import variables from "../theme/variables/commonColor";` but I don't see anywhere where `Modal` is called in the `commonColor` module. Help please?

**Comment by StevenBlack** [comment]
@stevehorn I'm guessing that it's more appropriate to submit this as a new issue, or ask in a support channel, like the [Native Base Slack channel](http://slack.nativebase.io/) for example.

Because it's never a good idea to string new unrelated issues on specific closed issues.

**Comment by SupriyaKalghatgi** [comment]
@stevehorn I tried fresh clone of `CRNA` branch, no issues for Android and iOS
